site_name: "nmapUnleashed Docs"
site_url: https://docs.nmap-unleashed.com
repo_url: https://github.com/sharkeonix/nmap-unleashed
site_dir: site
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: slate  # dark mode
      primary: cyan
      accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.expand
    - instant
nav:
  - nmapUnleashed(nu) Docs: README.md
  - âœ¨ Feature Summary: feature-summary.md
  - ğŸ“¦ Installation and Requirements: installation-and-requirements.md
  - ğŸš€ Quick Usage and Examples: quick-usage-and-examples.md
  - ğŸ§° Commands and Options: commands-and-options.md
  - âš™ï¸ Configuration and Presets: configuration-and-presets.md
  - ğŸ“Š Dashboard Overview: dashboard-overview.md
  - ğŸ› ï¸ Troubleshooting and FAQ: troubleshooting-and-faq.md
  - ğŸ¤ Contributing and Contact: contributing-and-contact.md
  - ğŸ“„ License: https://license.nmap-unleashed.com
  - ğŸ“œ Changelog: https://github.com/sharkeonix/nmap-unleashed/#-changelog
